name: Danger
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          event_path=${{ github.event_path }}

          if [ $GITHUB_EVENT_NAME = "pull_request_review" ]; then
            echo "Override event json file for pull_request_review event."

            event_path="event.json"
            cat ${{ github.event_path }} | jq '. |= .+ {"number": .pull_request.number}' > $event_path 
          fi

          GITHUB_EVENT_PATH=$event_path GITHUB_EVENT_NAME=pull_request bundle exec danger